# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

branches:
  # whitelist
  only:
    - master
    - main
    - prelease
    - ci/appveyor
    - appveyor
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
# skip_tags: true

# Start builds on tags only (GitHub, BitBucket, GitLab, Gitea)
# skip_non_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  matrix:
    - arch: x64
      qt: 6.3
      cc: VS2022
      mode: release
      QTDIR: C:\Qt\6.3\msvc2022_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

  init:
    - set vcarch=%arch%
    - if "%arch%" == "x64" set vcarch=amd64
    - if %cc%==VS2022 (
      call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %vcarch%
      ) else if not %cc%==MinGW (
      call "C:\Program Files (x86)\Microsoft Visual Studio %toolchain_version%.0\VC\vcvarsall.bat" %vcarch%
      )
    - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
    - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
    - echo QTDIR=%QTDIR%

  install:
    - git submodule update --init
    - mkdir build
    - cd build
    # - ..\tools\ci\win\install_dep.bat

  before_build:
    - set PATH=%QTDIR%\bin;%PATH%
    - if %cc%==MinGW set PATH=C:\Qt\Tools\mingw%toolchain_version%_32\bin;%PATH%
    - echo PATH=%PATH%

  build_script:
    # - ..\tools\ci\win\build.bat

  after_build:
    # - ..\tools\ci\win\deploy_win.bat

  test: off

  artifacts:
    - path: "jmbde*.7z" # relative to repo root
