version: "0.2"
files:
  - "**/*"
ignorePaths:
  - pnpm-lock.yaml
  - .git/
  - dist/
useGitignore: true
language: en, en-GB, de, de-DE
allowCompoundWords: true
enableGlobDot: true
words:
  - aarch
  - aminya
  - Amnet
  - anotherproj
  - applellvm
  - ARGN
  - asan
  - buildtools
  - ccache
  - ccmake
  - cflags
  - choco
  - cmake
  - cmakelint
  - cmds
  - codecov
  - codeql
  - cond
  - cpack
  - CPATH
  - Cppcheck
  - cppcoreguidelines
  - CPPFLAGS
  - cpprc
  - cppstd
  - cpptestproject
  - cpptools
  - ctest
  - Cuda
  - cxxflags
  - DCMAKE
  - deps
  - Dont
  - DOPT
  - dyld
  - dylib
  - eamodio
  - Eigen
  - fargs
  - fcolor
  - fdiagnostics
  - ftime
  - gcovr
  - gmock
  - Graphviz
  - gtest
  - hwrap
  - inplace
  - kcov
  - kwargs
  - LDFLAGS
  - libc
  - libcuda
  - libcxx
  - libdirs
  - libfmt
  - libstdc
  - LPSTR
  - LPWSTR
  - mdfile
  - mkdir
  - msbuild
  - msvc
  - msys
  - multilib
  - mylib
  - myprogram
  - myproj
  - myproject
  - nothrow
  - nvcc
  - Opencppcoverage
  - pargs
  - pnpm
  - PTRACE
  - pwsh
  - pylance
  - qtbase
  - qtdeclarative
  - qtimageformats
  - qtsvg
  - qttools
  - qttranslation
  - qttranslations
  - resdirs
  - rmrf
  - rpath
  - sccache
  - setx
  - shlib
  - spdlog
  - Struct
  - suppr
  - TOLOWER
  - TOUPPER
  - twxs
  - ubsan
  - vcpkg
  - vcvarsall
  - visualc
  - visualcpp
  - VSCMD
  - VSINSTALLDIR
  - vsversion
  - Wcast
  - Wconversion
  - Wdouble
  - Wduplicated
  - Werror
  - Weverything
  - Wextra
  - Wformat
  - Wlogical
  - Wmisleading
  - Wnon
  - Wnull
  - Woverloaded
  - Wpedantic
  - Wshadow
  - Wsign
  - Wunused
  - Wuseless
  - xcrun
  - Yahyaabadi
